language: c

sudo: false

env:
  global:
   - RACKET_DIR=~/racket
  matrix:
   - RACKET_VERSION=6.7
   - RACKET_VERSION=6.8
   - RACKET_VERSION=6.9
   - RACKET_VERSION=6.10
   - RACKET_VERSION=6.11
   - RACKET_VERSION=6.12
   - RACKET_VERSION=HEAD

matrix:
  allow_failures:
   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
 - cd ..
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
 - export PATH="${RACKET_DIR}/bin:${PATH}"

install:

before_script:

script:
 - raco pkg install --deps search-auto --link debug
 - raco test -p debug

after_script:
